language: python

python:
    - "3.6"
    - "3.7"
    - "3.8"

env:
    - DJANGO_VERSION=2.2 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=3.0 SAMPLE_PROJECT=sample_project
    - DJANGO_VERSION=3.1 SAMPLE_PROJECT=sample_project

branches:
    only:
        - develop

matrix:
    include:
        -
            python: "3.5"
            env: DJANGO_VERSION=2.2 SAMPLE_PROJECT=sample_project

install:
    - pip install django==$DJANGO_VERSION

script:
    - cd $SAMPLE_PROJECT
    - python manage.py test
